### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by abakus00** [ThorbenSpankas/blockchain-developer-bootcamp-final-project#1]
Hi @ThorbenSpankas,

Please can you resolve the compilation error with your contract? - See attached - error relates to priceorakle,.sol

Once you have resolved and tested your changes please resubmit ASAP.

Thank you
Amma
![Screenshot 2022-02-04 at 01 19 04](https://user-images.githubusercontent.com/69770572/152456574-18bb76ba-1b64-4eb1-b1ab-71faa90437d7.png)

**Comment by ThorbenSpankas** [comment]
Hi,

sorry for the issue. Hope all is working now. The compilation at least  
works. For the test, it remains a problem that my internet is to  
unstable to check (see screencast) if you have the same issue you  
might need to try several times. The problem is that some of the test  
require orakle data from chainlink so test need to be done on rinkeby.

Please let me know if I can help with anything else.

Best,

Thorben

https://github.com/ThorbenSpankas/blockchain-developer-bootcamp-final-project


Quoting abakus00 ***@***.***>:
